# Generated by Django 5.1.6 on 2025-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=11)),
                ('instituicao', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='motorista',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
