# Generated by Django 5.1.6 on 2025-03-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_alunos_alter_motorista_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ponto_partida', models.CharField(max_length=100)),
                ('ponto_destino', models.CharField(max_length=100)),
                ('horario_saida', models.TimeField()),
                ('horario_chegada', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('capacidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('onibus', 'Ônibus'), ('van', 'Van'), ('micro', 'Micro-ônibus')], max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='rota.motorista')),
            ],
        ),
    ]
