# Generated by Django 5.1.6 on 2025-04-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0004_confirmacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
